### ISSUE TITLE
Export TimeArbitraries

### ISSUE THREAD

**Issue by cquiroz** [typelevel/cats-time#193]
It would be nice to use `TimeArbitraries` outside `cats-time`. Perhaps it could use the `testkit` style to make it importable
Thanks

**Comment by lukoyanov** [comment]
I can extract time arbitraries into a separate `cats-time-testkit` module if this issue is still relevant. @cquiroz what do you think?

**Comment by cquiroz** [comment]
Yes, it would be useful. Maybe we should try to get #290 merged first

**Comment by cquiroz** [comment]
Solved by #293
