### ISSUE TITLE
scala-native 0.5.1 release would be great

### ISSUE THREAD

**Issue by yuriy-yarosh** [typelevel/cats-time#390]
As far as I've understood scala-native [was introduced](https://github.com/typelevel/cats-time/blob/main/build.sbt#L69) in 0.5.1, according to the version mapping

```scala
lazy val commonNativeSettings = Seq(
  tlVersionIntroduced := List("2.12", "2.13", "3").map(_ -> "0.5.1").toMap
)
```

It would be great to make a fresh release of this lib, with the respective scala-native support.
* I had some issues with 0.4.7 `sbt-scala-native` plugin, maybe worth downgrading to 0.4.5

**Comment by yuriy-yarosh** [comment]
Yup, 0.5.0 snapshot was released manually, so I'm closing this.

**Comment by armanbilge** [comment]
@yuriy-yarosh actually this should be left open, until 0.5.1 is published. We still don't have a stable release with Scala Native support.

**Comment by armanbilge** [comment]
Finally we can close 🎉 
https://github.com/typelevel/cats-time/releases/tag/v0.5.1

**Comment by valencik** [comment]
Yes, v0.5.1 has been released :)

A note for @typelevel/cats-time folks: the GH actions for publishing initially failed due to old deployment secrets which we’ve now removed as sbt-typelevel will use the org secrets.
